language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8
env:
  global:
    - CC=clang
    - CXX=clang++
  matrix:
    - NODE_VERSION=6
    - NODE_VERSION=7
    - NODE_VERSION=8
    - NODE_VERSION=9
    - NODE_VERSION=10
    - NODE_VERSION=12
cache:
  directories:
  - node_modules
before_install:
- nvm install $NODE_VERSION
- node --version
- python --version
install:
- npm install
- npm install -g coveralls nyc
script:
- npm run test:coverage
after_success:
- nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: never
    on_failure: change
